version: '3.7'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password

  pgbouncer:
    build: ./pgbouncer
    ports:
      - "6432:6432"
    depends_on:
      - postgres
